#############################################################################
# Makefile for building: untitled1
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  ../untitled1/untitled1.pro
# Template: aux
# Command: /Users/teun/Qt/5.15.2/ios/bin/qmake -o Makefile ../untitled1/untitled1.pro -spec macx-ios-clang CONFIG+=iphoneos CONFIG+=device CONFIG+=qml_debug -after
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
CXX           = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
DEFINES       = -DQT_COMPILER_SUPPORTS_SSE2 -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g $(EXPORT_ARCH_ARGS) $(EXPORT_QMAKE_XARCH_CFLAGS) -fobjc-nonfragile-abi -fobjc-legacy-dispatch -fembed-bitcode-marker -Wall -Wextra -ffunction-sections -fdata-sections -fPIC $(DEFINES)
CXXFLAGS      = -pipe -stdlib=libc++ -g -std=gnu++1z $(EXPORT_ARCH_ARGS) $(EXPORT_QMAKE_XARCH_CFLAGS) -fobjc-nonfragile-abi -fobjc-legacy-dispatch -fembed-bitcode-marker -Wall -Wextra -ffunction-sections -fdata-sections -fPIC $(DEFINES)
INCPATH       = -I../untitled1 -I. -I../Qt/5.15.2/ios/mkspecs/common/uikit -I../Qt/5.15.2/ios/include -I../Qt/5.15.2/ios/include/QtWidgets -I../Qt/5.15.2/ios/include/QtGui -I../Qt/5.15.2/ios/include/QtCore -I. -I. -I../Qt/5.15.2/ios/mkspecs/macx-ios-clang
QMAKE         = /Users/teun/Qt/5.15.2/ios/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /Users/teun/Qt/5.15.2/ios/bin/qmake -install qinstall
QINSTALL_PROGRAM = /Users/teun/Qt/5.15.2/ios/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = untitled11.0.0
DISTDIR = /Users/teun/build-untitled1-Qt_5_15_2_for_iOS-Debug/.tmp/untitled11.0.0
LINK          = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
LFLAGS        = -stdlib=libc++ $(EXPORT_ARCH_ARGS) $(EXPORT_QMAKE_XARCH_LFLAGS) -fembed-bitcode-marker -Wl,-e,_qt_main_wrapper -Wl,-dead_strip -Wl,-rpath,@executable_path/Frameworks
LIBS          = $(SUBLIBS) -L/Users/teun/Qt/5.15.2/ios/plugins/platforms -lqios /Users/teun/Qt/5.15.2/ios/plugins/platforms/libqios.a -framework QuartzCore -framework AudioToolbox -framework AssetsLibrary /Users/teun/Qt/5.15.2/ios/lib/libQt5FontDatabaseSupport.a /Users/teun/Qt/5.15.2/ios/lib/libqtfreetype.a /Users/teun/Qt/5.15.2/ios/lib/libQt5GraphicsSupport.a /Users/teun/Qt/5.15.2/ios/lib/libQt5ClipboardSupport.a /Users/teun/Qt/5.15.2/ios/plugins/imageformats/libqgif.a /Users/teun/Qt/5.15.2/ios/plugins/imageformats/libqicns.a /Users/teun/Qt/5.15.2/ios/plugins/imageformats/libqico.a /Users/teun/Qt/5.15.2/ios/plugins/imageformats/libqjpeg.a /Users/teun/Qt/5.15.2/ios/plugins/imageformats/libqmacheif.a /Users/teun/Qt/5.15.2/ios/plugins/imageformats/libqmacjp2.a -framework ImageIO /Users/teun/Qt/5.15.2/ios/plugins/imageformats/libqtga.a /Users/teun/Qt/5.15.2/ios/plugins/imageformats/libqtiff.a /Users/teun/Qt/5.15.2/ios/plugins/imageformats/libqwbmp.a /Users/teun/Qt/5.15.2/ios/plugins/imageformats/libqwebp.a /Users/teun/Qt/5.15.2/ios/lib/libQt5Widgets.a /Users/teun/Qt/5.15.2/ios/lib/libQt5Gui.a -framework Metal /Users/teun/Qt/5.15.2/ios/lib/libqtlibpng.a /Users/teun/Qt/5.15.2/ios/lib/libqtharfbuzz.a -framework CoreText -framework CoreGraphics /Users/teun/Qt/5.15.2/ios/lib/libQt5Core.a -framework MobileCoreServices -lm -framework UIKit -framework CoreFoundation -framework Foundation -lz /Users/teun/Qt/5.15.2/ios/lib/libqtpcre2.a -framework OpenGLES   
AR            = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ar cq
RANLIB        = /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ranlib -s
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       =  /Users/teun/build-untitled1-Qt_5_15_2_for_iOS-Debug/untitled1_plugin_import.cpp
OBJECTS       = untitled1_plugin_import.o
DIST          = ../Qt/5.15.2/ios/mkspecs/features/spec_pre.prf \
		../Qt/5.15.2/ios/mkspecs/qdevice.pri \
		../Qt/5.15.2/ios/mkspecs/features/device_config.prf \
		../Qt/5.15.2/ios/mkspecs/common/unix.conf \
		../Qt/5.15.2/ios/mkspecs/common/mac.conf \
		../Qt/5.15.2/ios/mkspecs/common/uikit.conf \
		../Qt/5.15.2/ios/mkspecs/common/ios.conf \
		../Qt/5.15.2/ios/mkspecs/common/sanitize.conf \
		../Qt/5.15.2/ios/mkspecs/common/gcc-base.conf \
		../Qt/5.15.2/ios/mkspecs/common/gcc-base-mac.conf \
		../Qt/5.15.2/ios/mkspecs/common/clang.conf \
		../Qt/5.15.2/ios/mkspecs/common/clang-mac.conf \
		../Qt/5.15.2/ios/mkspecs/common/uikit/clang.conf \
		../Qt/5.15.2/ios/mkspecs/common/uikit/qmake.conf \
		../Qt/5.15.2/ios/mkspecs/qconfig.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3danimation.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3danimation_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dcore.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dextras.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dextras_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dinput.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dlogic.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dquick.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dquickextras.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dquickinput.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dquickrender.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3drender.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3drender_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_core.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_core_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_edid_support_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_fb_support_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_gamepad.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_gamepad_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_gui.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_help.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_help_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_location.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_location_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_macextras.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_macextras_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_network.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_network_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_nfc.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_opengl.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_positioning.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_positioningquick.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_qml.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_qmlmodels.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_quick.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_remoteobjects.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_repparser.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_repparser_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_scxml.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_scxml_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_sensors.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_sql.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_svg.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_testlib.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_texttospeech.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_theme_support_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_uiplugin.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_uitools.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_webchannel.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_websockets.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_webview.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_webview_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_widgets.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_xml.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_zlib_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_darwingamepad.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_defaultgeometryloader.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_gltfgeometryloader.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_gltfsceneexport.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_gltfsceneimport.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_openglrenderer.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qavfcamera.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qavfmediaplayer.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qgif.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qicns.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qico.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qios.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qiosnsphotolibrarysupport.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qjpeg.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qmacheif.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qmacjp2.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qminimal.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qmldbg_debugger.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qmldbg_local.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qmldbg_messages.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qmldbg_native.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qmldbg_preview.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qmldbg_profiler.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qmldbg_server.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qsqlite.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qsvg.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qsvgicon.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtexttospeech_speechios.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtga.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtgeoservices_itemsoverlay.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapboxgl.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtiff.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtposition_cl.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtsensors_ios.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtwebview_darwin.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qwbmp.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qwebp.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_scene2d.pri \
		../Qt/5.15.2/ios/mkspecs/features/qt_functions.prf \
		../Qt/5.15.2/ios/mkspecs/features/qt_config.prf \
		../Qt/5.15.2/ios/mkspecs/macx-ios-clang/qmake.conf \
		../Qt/5.15.2/ios/mkspecs/features/spec_post.prf \
		../Qt/5.15.2/ios/mkspecs/features/exclusive_builds.prf \
		../Qt/5.15.2/ios/mkspecs/features/mac/sdk.prf \
		../Qt/5.15.2/ios/mkspecs/features/uikit/sdk.prf \
		../Qt/5.15.2/ios/mkspecs/features/toolchain.prf \
		../Qt/5.15.2/ios/mkspecs/features/mac/toolchain.prf \
		../Qt/5.15.2/ios/mkspecs/features/default_pre.prf \
		../Qt/5.15.2/ios/mkspecs/features/mac/default_pre.prf \
		../Qt/5.15.2/ios/mkspecs/features/uikit/default_pre.prf \
		../Qt/5.15.2/ios/mkspecs/features/resolve_config.prf \
		../Qt/5.15.2/ios/mkspecs/features/uikit/resolve_config.prf \
		../Qt/5.15.2/ios/mkspecs/features/exclusive_builds_post.prf \
		../Qt/5.15.2/ios/mkspecs/features/uikit/exclusive_builds_post.prf \
		../Qt/5.15.2/ios/mkspecs/features/default_post.prf \
		../Qt/5.15.2/ios/mkspecs/features/mac/default_post.prf \
		../Qt/5.15.2/ios/mkspecs/features/uikit/default_post.prf \
		../Qt/5.15.2/ios/mkspecs/macx-ios-clang/features/default_post.prf \
		../Qt/5.15.2/ios/mkspecs/features/mac/objective_c.prf \
		../Qt/5.15.2/ios/mkspecs/features/qml_debug.prf \
		../Qt/5.15.2/ios/mkspecs/features/mac/mac.prf \
		../Qt/5.15.2/ios/mkspecs/features/uikit/bitcode.prf \
		../Qt/5.15.2/ios/mkspecs/features/warn_on.prf \
		../Qt/5.15.2/ios/plugins/platforms/libqios.prl \
		../Qt/5.15.2/ios/mkspecs/features/qt.prf \
		../Qt/5.15.2/ios/mkspecs/features/uikit/qt.prf \
		../Qt/5.15.2/ios/mkspecs/features/gc_binaries.prf \
		../Qt/5.15.2/ios/mkspecs/features/uikit/gc_binaries.prf \
		../Qt/5.15.2/ios/mkspecs/features/resources_functions.prf \
		../Qt/5.15.2/ios/mkspecs/features/resources.prf \
		../Qt/5.15.2/ios/mkspecs/features/moc.prf \
		../Qt/5.15.2/ios/mkspecs/features/unix/opengl.prf \
		../Qt/5.15.2/ios/mkspecs/features/uic.prf \
		../Qt/5.15.2/ios/mkspecs/features/unix/thread.prf \
		../Qt/5.15.2/ios/mkspecs/features/qmake_use.prf \
		../Qt/5.15.2/ios/mkspecs/features/file_copies.prf \
		../Qt/5.15.2/ios/mkspecs/features/mac/rez.prf \
		../Qt/5.15.2/ios/mkspecs/features/mac/asset_catalogs.prf \
		../Qt/5.15.2/ios/mkspecs/features/uikit/testcase_targets.prf \
		../Qt/5.15.2/ios/mkspecs/features/exceptions.prf \
		../Qt/5.15.2/ios/mkspecs/features/yacc.prf \
		../Qt/5.15.2/ios/mkspecs/features/lex.prf \
		../Qt/5.15.2/ios/mkspecs/features/uikit/xcodebuild.prf \
		../untitled1/untitled1.pro mainwindow.h 
QMAKE_TARGET  = untitled1
DESTDIR       = 
TARGET        = untitled1
TARGETA       = 
TARGET0       = 
TARGETD       = 
TARGET1       = 
TARGET2       = 

####### Custom Variables
EXPORT_VALID_ARCHS = arm64 x86_64
EXPORT_ACTIVE_ARCHS = $(filter $(EXPORT_VALID_ARCHS), $(ARCHS))
EXPORT_ARCH_ARGS = $(foreach arch, $(if $(EXPORT_ACTIVE_ARCHS), $(EXPORT_ACTIVE_ARCHS), $(EXPORT_VALID_ARCHS)), -arch $(arch))
EXPORT_QMAKE_XARCH_CFLAGS = $(EXPORT_QMAKE_XARCH_CFLAGS_arm64) $(EXPORT_QMAKE_XARCH_CFLAGS_x86_64)
EXPORT_QMAKE_XARCH_LFLAGS = $(EXPORT_QMAKE_XARCH_LFLAGS_arm64) $(EXPORT_QMAKE_XARCH_LFLAGS_x86_64)
EXPORT_QMAKE_XARCH_CFLAGS_arm64 = -Xarch_arm64 -miphoneos-version-min=12.0 -Xarch_arm64 -isysroot/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.4.sdk
EXPORT_QMAKE_XARCH_LFLAGS_arm64 = -Xarch_arm64 -miphoneos-version-min=12.0 -Xarch_arm64 -isysroot/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.4.sdk
EXPORT_QMAKE_XARCH_CFLAGS_x86_64 = -Xarch_x86_64 -mios-simulator-version-min=12.0 -Xarch_x86_64 -isysroot/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.4.sdk
EXPORT_QMAKE_XARCH_LFLAGS_x86_64 = -Xarch_x86_64 -mios-simulator-version-min=12.0 -Xarch_x86_64 -isysroot/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator16.4.sdk
EXPORT__PRO_FILE_ = /Users/teun/untitled1/untitled1.pro
EXPORT_PRE_TARGETDEPS = /Users/teun/Qt/5.15.2/ios/lib/libQt5Widgets.a /Users/teun/Qt/5.15.2/ios/lib/libQt5Gui.a /Users/teun/Qt/5.15.2/ios/lib/libQt5Core.a
EXPORT_SUBTARGETS = debug-device debug-simulator release-device release-simulator
EXPORT_DEVICE_SDK = iphoneos
EXPORT_SIMULATOR_SDK = iphonesimulator
EXPORT_DEVICE_FILTER = --platform iOS --minimum-deployment-target 12.0
EXPORT_GENERIC_DEVICE_DESTINATION = generic/platform=iOS


include /Users/teun/Qt/5.15.2/ios/mkspecs/features/uikit/xcodebuild.mk
first:
####### Build rules

untitled1: /Users/teun/Qt/5.15.2/ios/lib/libQt5Widgets.a /Users/teun/Qt/5.15.2/ios/lib/libQt5Gui.a /Users/teun/Qt/5.15.2/ios/lib/libQt5Core.a $(OBJECTS)  
	

Makefile: ../untitled1/untitled1.pro ../Qt/5.15.2/ios/mkspecs/macx-ios-clang/qmake.conf ../Qt/5.15.2/ios/mkspecs/features/spec_pre.prf \
		../Qt/5.15.2/ios/mkspecs/qdevice.pri \
		../Qt/5.15.2/ios/mkspecs/features/device_config.prf \
		../Qt/5.15.2/ios/mkspecs/common/unix.conf \
		../Qt/5.15.2/ios/mkspecs/common/mac.conf \
		../Qt/5.15.2/ios/mkspecs/common/uikit.conf \
		../Qt/5.15.2/ios/mkspecs/common/ios.conf \
		../Qt/5.15.2/ios/mkspecs/common/sanitize.conf \
		../Qt/5.15.2/ios/mkspecs/common/gcc-base.conf \
		../Qt/5.15.2/ios/mkspecs/common/gcc-base-mac.conf \
		../Qt/5.15.2/ios/mkspecs/common/clang.conf \
		../Qt/5.15.2/ios/mkspecs/common/clang-mac.conf \
		../Qt/5.15.2/ios/mkspecs/common/uikit/clang.conf \
		../Qt/5.15.2/ios/mkspecs/common/uikit/qmake.conf \
		../Qt/5.15.2/ios/mkspecs/qconfig.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3danimation.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3danimation_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dcore.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dcore_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dextras.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dextras_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dinput.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dinput_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dlogic.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dlogic_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dquick.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dquick_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dquickanimation.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dquickanimation_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dquickextras.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dquickextras_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dquickinput.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dquickrender.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dquickscene2d.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dquickscene2d_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3drender.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3drender_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_bluetooth.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_bluetooth_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_bootstrap_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_clipboard_support_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_concurrent.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_concurrent_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_core.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_core_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_edid_support_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_fb_support_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_gamepad.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_gamepad_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_graphics_support_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_gui.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_gui_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_help.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_help_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_location.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_location_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_macextras.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_macextras_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_multimedia.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_multimedia_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_multimediawidgets.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_network.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_network_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_nfc.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_nfc_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_opengl.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_opengl_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_openglextensions.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_openglextensions_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_positioning.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_positioning_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_positioningquick.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_positioningquick_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_qml.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_qml_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_qmldebug_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_qmlmodels.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_qmltest.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_qmltest_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_quick.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_quick_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_quickcontrols2.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_quickparticles_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_quickshapes_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_quicktemplates2.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_quickwidgets.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_remoteobjects.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_remoteobjects_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_repparser.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_repparser_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_scxml.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_scxml_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_sensors.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_sensors_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_sql.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_sql_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_svg.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_svg_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_testlib.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_testlib_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_texttospeech.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_texttospeech_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_theme_support_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_uiplugin.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_uitools.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_uitools_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_webchannel.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_webchannel_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_websockets.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_websockets_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_webview.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_webview_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_widgets.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_widgets_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_xml.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_xml_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_xmlpatterns.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_lib_zlib_private.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_darwingamepad.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_defaultgeometryloader.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_gltfgeometryloader.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_gltfsceneexport.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_gltfsceneimport.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_openglrenderer.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qavfcamera.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qavfmediaplayer.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qgenericbearer.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qgif.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qicns.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qico.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qios.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qiosnsphotolibrarysupport.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qjpeg.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qmacheif.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qmacjp2.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qminimal.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qmldbg_debugger.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qmldbg_local.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qmldbg_messages.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qmldbg_native.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qmldbg_preview.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qmldbg_profiler.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qmldbg_server.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qoffscreen.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qsqlite.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qsvg.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qsvgicon.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtexttospeech_speechios.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtga.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtgeoservices_itemsoverlay.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapboxgl.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtiff.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtposition_cl.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtsensors_generic.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtsensors_ios.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtwebview_darwin.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qwbmp.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qwebp.pri \
		../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_scene2d.pri \
		../Qt/5.15.2/ios/mkspecs/features/qt_functions.prf \
		../Qt/5.15.2/ios/mkspecs/features/qt_config.prf \
		../Qt/5.15.2/ios/mkspecs/macx-ios-clang/qmake.conf \
		../Qt/5.15.2/ios/mkspecs/features/spec_post.prf \
		../Qt/5.15.2/ios/mkspecs/features/exclusive_builds.prf \
		../Qt/5.15.2/ios/mkspecs/features/mac/sdk.prf \
		../Qt/5.15.2/ios/mkspecs/features/uikit/sdk.prf \
		../Qt/5.15.2/ios/mkspecs/features/toolchain.prf \
		../Qt/5.15.2/ios/mkspecs/features/mac/toolchain.prf \
		../Qt/5.15.2/ios/mkspecs/features/default_pre.prf \
		../Qt/5.15.2/ios/mkspecs/features/mac/default_pre.prf \
		../Qt/5.15.2/ios/mkspecs/features/uikit/default_pre.prf \
		../Qt/5.15.2/ios/mkspecs/features/resolve_config.prf \
		../Qt/5.15.2/ios/mkspecs/features/uikit/resolve_config.prf \
		../Qt/5.15.2/ios/mkspecs/features/exclusive_builds_post.prf \
		../Qt/5.15.2/ios/mkspecs/features/uikit/exclusive_builds_post.prf \
		../Qt/5.15.2/ios/mkspecs/features/default_post.prf \
		../Qt/5.15.2/ios/mkspecs/features/mac/default_post.prf \
		../Qt/5.15.2/ios/mkspecs/features/uikit/default_post.prf \
		../Qt/5.15.2/ios/mkspecs/macx-ios-clang/features/default_post.prf \
		../Qt/5.15.2/ios/mkspecs/features/mac/objective_c.prf \
		../Qt/5.15.2/ios/mkspecs/features/qml_debug.prf \
		../Qt/5.15.2/ios/mkspecs/features/mac/mac.prf \
		../Qt/5.15.2/ios/mkspecs/features/uikit/bitcode.prf \
		../Qt/5.15.2/ios/mkspecs/features/warn_on.prf \
		../Qt/5.15.2/ios/plugins/platforms/libqios.prl \
		../Qt/5.15.2/ios/mkspecs/features/qt.prf \
		../Qt/5.15.2/ios/mkspecs/features/uikit/qt.prf \
		../Qt/5.15.2/ios/mkspecs/features/gc_binaries.prf \
		../Qt/5.15.2/ios/mkspecs/features/uikit/gc_binaries.prf \
		../Qt/5.15.2/ios/mkspecs/features/resources_functions.prf \
		../Qt/5.15.2/ios/mkspecs/features/resources.prf \
		../Qt/5.15.2/ios/mkspecs/features/moc.prf \
		../Qt/5.15.2/ios/mkspecs/features/unix/opengl.prf \
		../Qt/5.15.2/ios/mkspecs/features/uic.prf \
		../Qt/5.15.2/ios/mkspecs/features/unix/thread.prf \
		../Qt/5.15.2/ios/mkspecs/features/qmake_use.prf \
		../Qt/5.15.2/ios/mkspecs/features/file_copies.prf \
		../Qt/5.15.2/ios/mkspecs/features/mac/rez.prf \
		../Qt/5.15.2/ios/mkspecs/features/mac/asset_catalogs.prf \
		../Qt/5.15.2/ios/mkspecs/features/uikit/testcase_targets.prf \
		../Qt/5.15.2/ios/mkspecs/features/exceptions.prf \
		../Qt/5.15.2/ios/mkspecs/features/yacc.prf \
		../Qt/5.15.2/ios/mkspecs/features/lex.prf \
		../Qt/5.15.2/ios/mkspecs/features/uikit/xcodebuild.prf \
		../untitled1/untitled1.pro \
		../Qt/5.15.2/ios/lib/libQt5FontDatabaseSupport.prl \
		../Qt/5.15.2/ios/lib/libqtfreetype.prl \
		../Qt/5.15.2/ios/lib/libQt5GraphicsSupport.prl \
		../Qt/5.15.2/ios/lib/libQt5ClipboardSupport.prl \
		../Qt/5.15.2/ios/lib/libQt5Gui.prl \
		../Qt/5.15.2/ios/lib/libqtlibpng.prl \
		../Qt/5.15.2/ios/lib/libqtharfbuzz.prl \
		../Qt/5.15.2/ios/lib/libQt5Core.prl \
		../Qt/5.15.2/ios/lib/libqtpcre2.prl \
		../Qt/5.15.2/ios/plugins/imageformats/libqgif.prl \
		../Qt/5.15.2/ios/plugins/imageformats/libqicns.prl \
		../Qt/5.15.2/ios/plugins/imageformats/libqico.prl \
		../Qt/5.15.2/ios/plugins/imageformats/libqjpeg.prl \
		../Qt/5.15.2/ios/plugins/imageformats/libqmacheif.prl \
		../Qt/5.15.2/ios/plugins/imageformats/libqmacjp2.prl \
		../Qt/5.15.2/ios/plugins/imageformats/libqtga.prl \
		../Qt/5.15.2/ios/plugins/imageformats/libqtiff.prl \
		../Qt/5.15.2/ios/plugins/imageformats/libqwbmp.prl \
		../Qt/5.15.2/ios/plugins/imageformats/libqwebp.prl \
		../Qt/5.15.2/ios/lib/libQt5Widgets.prl
	$(QMAKE) -o Makefile ../untitled1/untitled1.pro -spec macx-ios-clang CONFIG+=iphoneos CONFIG+=device CONFIG+=qml_debug -after
../Qt/5.15.2/ios/mkspecs/features/spec_pre.prf:
../Qt/5.15.2/ios/mkspecs/qdevice.pri:
../Qt/5.15.2/ios/mkspecs/features/device_config.prf:
../Qt/5.15.2/ios/mkspecs/common/unix.conf:
../Qt/5.15.2/ios/mkspecs/common/mac.conf:
../Qt/5.15.2/ios/mkspecs/common/uikit.conf:
../Qt/5.15.2/ios/mkspecs/common/ios.conf:
../Qt/5.15.2/ios/mkspecs/common/sanitize.conf:
../Qt/5.15.2/ios/mkspecs/common/gcc-base.conf:
../Qt/5.15.2/ios/mkspecs/common/gcc-base-mac.conf:
../Qt/5.15.2/ios/mkspecs/common/clang.conf:
../Qt/5.15.2/ios/mkspecs/common/clang-mac.conf:
../Qt/5.15.2/ios/mkspecs/common/uikit/clang.conf:
../Qt/5.15.2/ios/mkspecs/common/uikit/qmake.conf:
../Qt/5.15.2/ios/mkspecs/qconfig.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3danimation.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3danimation_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dcore.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dcore_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dextras.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dextras_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dinput.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dinput_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dlogic.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dlogic_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dquick.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dquick_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dquickanimation.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dquickanimation_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dquickextras.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dquickextras_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dquickinput.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dquickinput_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dquickrender.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dquickrender_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dquickscene2d.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3dquickscene2d_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3drender.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_3drender_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_accessibility_support_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_bluetooth.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_bluetooth_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_bootstrap_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_clipboard_support_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_concurrent.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_concurrent_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_core.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_core_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_edid_support_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_fb_support_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_gamepad.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_gamepad_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_graphics_support_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_gui.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_gui_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_help.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_help_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_location.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_location_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_macextras.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_macextras_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_multimedia.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_multimedia_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_multimediawidgets.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_network.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_network_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_nfc.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_nfc_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_opengl.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_opengl_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_openglextensions.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_openglextensions_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_packetprotocol_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_positioning.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_positioning_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_positioningquick.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_positioningquick_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_qml.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_qml_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_qmldebug_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_qmldevtools_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_qmlmodels.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_qmlmodels_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_qmltest.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_qmltest_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_qmlworkerscript.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_quick.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_quick_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_quickcontrols2.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_quickparticles_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_quickshapes_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_quicktemplates2.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_quickwidgets.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_quickwidgets_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_remoteobjects.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_remoteobjects_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_repparser.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_repparser_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_scxml.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_scxml_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_sensors.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_sensors_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_sql.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_sql_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_svg.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_svg_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_testlib.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_testlib_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_texttospeech.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_texttospeech_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_theme_support_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_uiplugin.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_uitools.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_uitools_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_webchannel.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_webchannel_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_websockets.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_websockets_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_webview.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_webview_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_widgets.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_widgets_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_xml.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_xml_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_xmlpatterns.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_lib_zlib_private.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_darwingamepad.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_defaultgeometryloader.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_gltfgeometryloader.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_gltfsceneexport.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_gltfsceneimport.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_openglrenderer.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qavfcamera.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qavfmediaplayer.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qgenericbearer.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qgif.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qicns.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qico.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qios.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qiosnsphotolibrarysupport.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qjpeg.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qmacheif.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qmacjp2.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qminimal.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qmldbg_debugger.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qmldbg_inspector.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qmldbg_local.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qmldbg_messages.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qmldbg_native.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qmldbg_nativedebugger.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qmldbg_preview.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qmldbg_profiler.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qmldbg_quickprofiler.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qmldbg_server.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qmldbg_tcp.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qoffscreen.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qsqlite.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qsvg.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qsvgicon.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtaudio_coreaudio.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtexttospeech_speechios.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtga.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtgeoservices_esri.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtgeoservices_itemsoverlay.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapbox.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtgeoservices_mapboxgl.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtgeoservices_nokia.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtgeoservices_osm.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtiff.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtmedia_audioengine.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtmultimedia_m3u.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtposition_cl.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtposition_positionpoll.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtsensorgestures_plugin.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtsensorgestures_shakeplugin.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtsensors_generic.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtsensors_ios.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtuiotouchplugin.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qtwebview_darwin.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qwbmp.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_qwebp.pri:
../Qt/5.15.2/ios/mkspecs/modules/qt_plugin_scene2d.pri:
../Qt/5.15.2/ios/mkspecs/features/qt_functions.prf:
../Qt/5.15.2/ios/mkspecs/features/qt_config.prf:
../Qt/5.15.2/ios/mkspecs/macx-ios-clang/qmake.conf:
../Qt/5.15.2/ios/mkspecs/features/spec_post.prf:
../Qt/5.15.2/ios/mkspecs/features/exclusive_builds.prf:
../Qt/5.15.2/ios/mkspecs/features/mac/sdk.prf:
../Qt/5.15.2/ios/mkspecs/features/uikit/sdk.prf:
../Qt/5.15.2/ios/mkspecs/features/toolchain.prf:
../Qt/5.15.2/ios/mkspecs/features/mac/toolchain.prf:
../Qt/5.15.2/ios/mkspecs/features/default_pre.prf:
../Qt/5.15.2/ios/mkspecs/features/mac/default_pre.prf:
../Qt/5.15.2/ios/mkspecs/features/uikit/default_pre.prf:
../Qt/5.15.2/ios/mkspecs/features/resolve_config.prf:
../Qt/5.15.2/ios/mkspecs/features/uikit/resolve_config.prf:
../Qt/5.15.2/ios/mkspecs/features/exclusive_builds_post.prf:
../Qt/5.15.2/ios/mkspecs/features/uikit/exclusive_builds_post.prf:
../Qt/5.15.2/ios/mkspecs/features/default_post.prf:
../Qt/5.15.2/ios/mkspecs/features/mac/default_post.prf:
../Qt/5.15.2/ios/mkspecs/features/uikit/default_post.prf:
../Qt/5.15.2/ios/mkspecs/macx-ios-clang/features/default_post.prf:
../Qt/5.15.2/ios/mkspecs/features/mac/objective_c.prf:
../Qt/5.15.2/ios/mkspecs/features/qml_debug.prf:
../Qt/5.15.2/ios/mkspecs/features/mac/mac.prf:
../Qt/5.15.2/ios/mkspecs/features/uikit/bitcode.prf:
../Qt/5.15.2/ios/mkspecs/features/warn_on.prf:
../Qt/5.15.2/ios/plugins/platforms/libqios.prl:
../Qt/5.15.2/ios/mkspecs/features/qt.prf:
../Qt/5.15.2/ios/mkspecs/features/uikit/qt.prf:
../Qt/5.15.2/ios/mkspecs/features/gc_binaries.prf:
../Qt/5.15.2/ios/mkspecs/features/uikit/gc_binaries.prf:
../Qt/5.15.2/ios/mkspecs/features/resources_functions.prf:
../Qt/5.15.2/ios/mkspecs/features/resources.prf:
../Qt/5.15.2/ios/mkspecs/features/moc.prf:
../Qt/5.15.2/ios/mkspecs/features/unix/opengl.prf:
../Qt/5.15.2/ios/mkspecs/features/uic.prf:
../Qt/5.15.2/ios/mkspecs/features/unix/thread.prf:
../Qt/5.15.2/ios/mkspecs/features/qmake_use.prf:
../Qt/5.15.2/ios/mkspecs/features/file_copies.prf:
../Qt/5.15.2/ios/mkspecs/features/mac/rez.prf:
../Qt/5.15.2/ios/mkspecs/features/mac/asset_catalogs.prf:
../Qt/5.15.2/ios/mkspecs/features/uikit/testcase_targets.prf:
../Qt/5.15.2/ios/mkspecs/features/exceptions.prf:
../Qt/5.15.2/ios/mkspecs/features/yacc.prf:
../Qt/5.15.2/ios/mkspecs/features/lex.prf:
../Qt/5.15.2/ios/mkspecs/features/uikit/xcodebuild.prf:
../untitled1/untitled1.pro:
../Qt/5.15.2/ios/lib/libQt5FontDatabaseSupport.prl:
../Qt/5.15.2/ios/lib/libqtfreetype.prl:
../Qt/5.15.2/ios/lib/libQt5GraphicsSupport.prl:
../Qt/5.15.2/ios/lib/libQt5ClipboardSupport.prl:
../Qt/5.15.2/ios/lib/libQt5Gui.prl:
../Qt/5.15.2/ios/lib/libqtlibpng.prl:
../Qt/5.15.2/ios/lib/libqtharfbuzz.prl:
../Qt/5.15.2/ios/lib/libQt5Core.prl:
../Qt/5.15.2/ios/lib/libqtpcre2.prl:
../Qt/5.15.2/ios/plugins/imageformats/libqgif.prl:
../Qt/5.15.2/ios/plugins/imageformats/libqicns.prl:
../Qt/5.15.2/ios/plugins/imageformats/libqico.prl:
../Qt/5.15.2/ios/plugins/imageformats/libqjpeg.prl:
../Qt/5.15.2/ios/plugins/imageformats/libqmacheif.prl:
../Qt/5.15.2/ios/plugins/imageformats/libqmacjp2.prl:
../Qt/5.15.2/ios/plugins/imageformats/libqtga.prl:
../Qt/5.15.2/ios/plugins/imageformats/libqtiff.prl:
../Qt/5.15.2/ios/plugins/imageformats/libqwbmp.prl:
../Qt/5.15.2/ios/plugins/imageformats/libqwebp.prl:
../Qt/5.15.2/ios/lib/libQt5Widgets.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ../untitled1/untitled1.pro -spec macx-ios-clang CONFIG+=iphoneos CONFIG+=device CONFIG+=qml_debug -after

qmake_all: FORCE


all: Makefile untitled1

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) $(TARGET0) $(TARGET1) $(TARGET2) $(TARGETA)
	-$(DEL_FILE) /Users/teun/build-untitled1-Qt_5_15_2_for_iOS-Debug/untitled1_plugin_import.cpp
	-$(DEL_FILE) Makefile


####### Sub-libraries

debug: debug-device debug-simulator

device: debug-device release-device

simulator: debug-simulator release-simulator

release: release-device release-simulator

xcodeproj:
	@$(QMAKE) -spec macx-xcode "$(EXPORT__PRO_FILE_)" -spec macx-ios-clang CONFIG+=iphoneos CONFIG+=device CONFIG+=qml_debug -after

mocclean:

mocables:

distclean: clean_all distclean_xcodebuild

distclean_xcodebuild:
	-$(DEL_FILE) -R untitled1.xcodeproj Debug-device Debug-simulator Release-device Release-simulator

compiler_clean: 

####### Compile

untitled1_plugin_import.o: /Users/teun/build-untitled1-Qt_5_15_2_for_iOS-Debug/untitled1_plugin_import.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o untitled1_plugin_import.o /Users/teun/build-untitled1-Qt_5_15_2_for_iOS-Debug/untitled1_plugin_import.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

